-- Stint CRM · configuration every install needs (no people, no sample records)

insert into public.app_role (name, sort) values
  ('Admin', 0),
  ('Front desk', 1),
  ('Marketing', 2),
  ('Telecaller', 3),
  ('Sales', 4),
  ('HR / Counsellor', 5),
  ('Trainer', 6),
  ('SME', 7),
  ('Placement', 8),
  ('Finance', 9)
on conflict do nothing;

insert into public.page (id, grp, title, sort) values
  ('home', 'Home', 'Dashboard', 0),
  ('followups', 'Home', 'My follow-ups', 1),
  ('enquiry', 'Front desk', 'New enquiry', 2),
  ('enrolform', 'Front desk', 'Enrolment form', 3),
  ('campaign', 'Marketing', 'Campaigns', 4),
  ('source', 'Marketing', 'Lead sources', 5),
  ('lead', 'Telecalling', 'Leads', 6),
  ('call', 'Telecalling', 'Call logs', 7),
  ('recordings', 'Telecalling', 'Recordings', 8),
  ('counsel', 'Sales', 'Counselling', 9),
  ('quote', 'Sales', 'Fee quotes', 10),
  ('target', 'Sales', 'Sales targets', 11),
  ('candidate', 'Enrolment', 'Candidates', 12),
  ('program', 'Enrolment', 'Programs', 13),
  ('branch', 'Enrolment', 'Branches', 14),
  ('batch', 'Training', 'Batches', 15),
  ('attendance', 'Training', 'Attendance', 16),
  ('note', 'Training', 'Training notes', 17),
  ('mock', 'Mocks', 'Mock sessions', 18),
  ('sme', 'Mocks', 'SME feedback', 19),
  ('resume', 'Resume & docs', 'Resumes', 20),
  ('doc', 'Resume & docs', 'Documents', 21),
  ('vendor', 'Resume & docs', 'Vendor requests', 22),
  ('jobdocs', 'Resume & docs', 'Job papers', 23),
  ('placement', 'Placement', 'Placements', 24),
  ('checklist', 'Placement', 'Placement checklist', 25),
  ('alumni', 'Alumni', 'Alumni', 26),
  ('plan', 'Fees', 'Fee plans', 27),
  ('payment', 'Fees', 'Payments', 28),
  ('alert', 'Ops', 'Alerts', 29),
  ('history', 'Ops', 'Status history', 30),
  ('company', 'Ops', 'Companies', 31),
  ('rep_funnel', 'Reports', 'Lead funnel report', 32),
  ('rep_roi', 'Reports', 'Campaign ROI report', 33),
  ('rep_batch', 'Reports', 'Batch performance report', 34),
  ('rep_place', 'Reports', 'Placement report', 35),
  ('rep_cash', 'Reports', 'Collections report', 36),
  ('users', 'Admin settings', 'Users & staff', 37),
  ('roles', 'Admin settings', 'Roles & permissions', 38),
  ('assign', 'Admin settings', 'Assignment rules', 39),
  ('followrules', 'Admin settings', 'Follow-up and stuck rules', 40),
  ('dropdowns', 'Admin settings', 'Dropdown values', 41),
  ('imports', 'Admin settings', 'Import / export', 42),
  ('automations', 'Admin settings', 'Automations', 43),
  ('connections', 'Admin settings', 'Connections', 44),
  ('branding', 'Admin settings', 'Branding & sidebar', 45)
on conflict (id) do update set grp = excluded.grp, title = excluded.title, sort = excluded.sort;

insert into public.role_page_access (role, page_id, mode) values
  ('Front desk', 'home', 'w'),
  ('Front desk', 'followups', 'w'),
  ('Front desk', 'enquiry', 'w'),
  ('Front desk', 'enrolform', 'w'),
  ('Front desk', 'lead', 'r'),
  ('Front desk', 'recordings', 'w'),
  ('Front desk', 'candidate', 'r'),
  ('Front desk', 'doc', 'w'),
  ('Marketing', 'home', 'w'),
  ('Marketing', 'followups', 'w'),
  ('Marketing', 'campaign', 'w'),
  ('Marketing', 'source', 'w'),
  ('Marketing', 'lead', 'r'),
  ('Marketing', 'alert', 'r'),
  ('Telecaller', 'home', 'w'),
  ('Telecaller', 'followups', 'w'),
  ('Telecaller', 'lead', 'w'),
  ('Telecaller', 'call', 'w'),
  ('Telecaller', 'recordings', 'w'),
  ('Telecaller', 'counsel', 'r'),
  ('Telecaller', 'alert', 'r'),
  ('Sales', 'home', 'w'),
  ('Sales', 'followups', 'w'),
  ('Sales', 'lead', 'w'),
  ('Sales', 'call', 'r'),
  ('Sales', 'recordings', 'w'),
  ('Sales', 'counsel', 'w'),
  ('Sales', 'quote', 'w'),
  ('Sales', 'target', 'r'),
  ('Sales', 'candidate', 'r'),
  ('Sales', 'program', 'r'),
  ('Sales', 'plan', 'r'),
  ('Sales', 'payment', 'r'),
  ('HR / Counsellor', 'home', 'w'),
  ('HR / Counsellor', 'followups', 'w'),
  ('HR / Counsellor', 'enrolform', 'w'),
  ('HR / Counsellor', 'candidate', 'w'),
  ('HR / Counsellor', 'batch', 'r'),
  ('HR / Counsellor', 'attendance', 'r'),
  ('HR / Counsellor', 'mock', 'w'),
  ('HR / Counsellor', 'sme', 'r'),
  ('HR / Counsellor', 'resume', 'w'),
  ('HR / Counsellor', 'doc', 'w'),
  ('HR / Counsellor', 'vendor', 'w'),
  ('HR / Counsellor', 'jobdocs', 'w'),
  ('HR / Counsellor', 'placement', 'r'),
  ('HR / Counsellor', 'checklist', 'w'),
  ('HR / Counsellor', 'alert', 'r'),
  ('HR / Counsellor', 'history', 'r'),
  ('Trainer', 'home', 'w'),
  ('Trainer', 'followups', 'w'),
  ('Trainer', 'candidate', 'r'),
  ('Trainer', 'batch', 'w'),
  ('Trainer', 'attendance', 'w'),
  ('Trainer', 'note', 'w'),
  ('Trainer', 'mock', 'w'),
  ('Trainer', 'sme', 'r'),
  ('SME', 'home', 'w'),
  ('SME', 'followups', 'w'),
  ('SME', 'candidate', 'r'),
  ('SME', 'mock', 'w'),
  ('SME', 'sme', 'w'),
  ('Placement', 'home', 'w'),
  ('Placement', 'followups', 'w'),
  ('Placement', 'candidate', 'r'),
  ('Placement', 'resume', 'r'),
  ('Placement', 'doc', 'r'),
  ('Placement', 'jobdocs', 'r'),
  ('Placement', 'placement', 'w'),
  ('Placement', 'checklist', 'w'),
  ('Placement', 'alumni', 'w'),
  ('Placement', 'company', 'w'),
  ('Finance', 'home', 'w'),
  ('Finance', 'followups', 'w'),
  ('Finance', 'candidate', 'r'),
  ('Finance', 'program', 'r'),
  ('Finance', 'plan', 'w'),
  ('Finance', 'payment', 'w'),
  ('Finance', 'alert', 'r')
on conflict do nothing;

insert into public.role_field_access (role, field_group, mode) values
  ('Front desk', 'contact', 'f'),
  ('Front desk', 'family', 'f'),
  ('Front desk', 'identity', 'm'),
  ('Front desk', 'bank', 'h'),
  ('Marketing', 'contact', 'h'),
  ('Marketing', 'family', 'h'),
  ('Marketing', 'identity', 'h'),
  ('Marketing', 'bank', 'h'),
  ('Telecaller', 'contact', 'f'),
  ('Telecaller', 'family', 'h'),
  ('Telecaller', 'identity', 'h'),
  ('Telecaller', 'bank', 'h'),
  ('Sales', 'contact', 'f'),
  ('Sales', 'family', 'h'),
  ('Sales', 'identity', 'h'),
  ('Sales', 'bank', 'h'),
  ('HR / Counsellor', 'contact', 'f'),
  ('HR / Counsellor', 'family', 'f'),
  ('HR / Counsellor', 'identity', 'f'),
  ('HR / Counsellor', 'bank', 'f'),
  ('Trainer', 'contact', 'm'),
  ('Trainer', 'family', 'h'),
  ('Trainer', 'identity', 'h'),
  ('Trainer', 'bank', 'h'),
  ('SME', 'contact', 'm'),
  ('SME', 'family', 'h'),
  ('SME', 'identity', 'h'),
  ('SME', 'bank', 'h'),
  ('Placement', 'contact', 'f'),
  ('Placement', 'family', 'h'),
  ('Placement', 'identity', 'm'),
  ('Placement', 'bank', 'h'),
  ('Finance', 'contact', 'f'),
  ('Finance', 'family', 'h'),
  ('Finance', 'identity', 'm'),
  ('Finance', 'bank', 'f')
on conflict do nothing;

insert into public.dropdown_list (id, name, used_on) values
  ('lead_stage', 'Lead stage', 'Leads'),
  ('call_outcome', 'Call outcome', 'Call logs'),
  ('lead_source_type', 'Lead source type', 'Lead sources'),
  ('preferred_mode', 'Preferred mode', 'New enquiry'),
  ('preferred_start', 'Preferred start', 'New enquiry'),
  ('currently', 'Currently', 'New enquiry'),
  ('counselling_status', 'Counselling status', 'Counselling'),
  ('quote_status', 'Fee quote status', 'Fee quotes'),
  ('payment_plan', 'Payment plan', 'Fee quotes, Fee plans'),
  ('candidate_stage', 'Candidate stage', 'Candidates'),
  ('attendance_mark', 'Attendance mark', 'Attendance'),
  ('training_flag', 'Training progress', 'Training notes'),
  ('mock_level', 'Mock level', 'Mock sessions'),
  ('mock_status', 'Mock result', 'Mock sessions'),
  ('verdict', 'SME verdict', 'SME feedback'),
  ('resume_status', 'Resume status', 'Resumes'),
  ('document_type', 'Document type', 'Documents'),
  ('document_status', 'Document status', 'Documents'),
  ('vendor', 'Vendor', 'Vendor requests'),
  ('vendor_request_type', 'Vendor request type', 'Vendor requests'),
  ('request_status', 'Request status', 'Vendor requests, Job papers'),
  ('pf_status', 'PF status', 'Job papers'),
  ('paper_status', 'Paper status', 'Job papers'),
  ('placement_status', 'Placement status', 'Placements'),
  ('checklist_status', 'Checklist status', 'Placement checklist'),
  ('payment_mode', 'Payment mode', 'Payments'),
  ('payment_status', 'Payment status', 'Payments'),
  ('campaign_channel', 'Campaign channel', 'Campaigns'),
  ('campaign_status', 'Campaign status', 'Campaigns'),
  ('priority', 'Priority', 'Alerts'),
  ('company_status', 'Company status', 'Companies'),
  ('branch_mode', 'Branch mode', 'Branches'),
  ('batch_status', 'Batch status', 'Batches')
on conflict do nothing;

insert into public.dropdown_value (list_id, value, sort, locked) values
  ('lead_stage', 'New', 0, true),
  ('lead_stage', 'Callback', 1, false),
  ('lead_stage', 'Interested', 2, false),
  ('lead_stage', 'Counselling', 3, false),
  ('lead_stage', 'Converted', 4, true),
  ('lead_stage', 'Not interested', 5, false),
  ('call_outcome', 'Connected', 0, false),
  ('call_outcome', 'No answer', 1, false),
  ('call_outcome', 'Callback', 2, false),
  ('call_outcome', 'Interested', 3, false),
  ('call_outcome', 'Not interested', 4, false),
  ('call_outcome', 'Booked counselling', 5, false),
  ('call_outcome', 'Wrong number', 6, false),
  ('lead_source_type', 'Paid', 0, false),
  ('lead_source_type', 'Organic', 1, false),
  ('lead_source_type', 'Referral', 2, false),
  ('lead_source_type', 'Offline', 3, false),
  ('preferred_mode', 'Classroom', 0, false),
  ('preferred_mode', 'Online', 1, false),
  ('preferred_mode', 'Hybrid', 2, false),
  ('preferred_start', 'This month', 0, false),
  ('preferred_start', 'Next month', 1, false),
  ('preferred_start', 'In 2-3 months', 2, false),
  ('preferred_start', 'Not sure', 3, false),
  ('currently', 'Student', 0, false),
  ('currently', 'Working', 1, false),
  ('currently', 'Looking for a job', 2, false),
  ('currently', 'Career break', 3, false),
  ('counselling_status', 'Booked', 0, false),
  ('counselling_status', 'Done', 1, false),
  ('counselling_status', 'Won', 2, false),
  ('counselling_status', 'No-show', 3, false),
  ('quote_status', 'Sent', 0, false),
  ('quote_status', 'Negotiating', 1, false),
  ('quote_status', 'Accepted', 2, true),
  ('quote_status', 'Expired', 3, false),
  ('payment_plan', 'Full payment', 0, false),
  ('payment_plan', '2 instalments', 1, false),
  ('payment_plan', '3 instalments', 2, false),
  ('candidate_stage', 'Enrolled', 0, true),
  ('candidate_stage', 'Training', 1, false),
  ('candidate_stage', 'Mocks', 2, false),
  ('candidate_stage', 'Resume', 3, false),
  ('candidate_stage', 'Docs', 4, false),
  ('candidate_stage', 'Ready', 5, false),
  ('candidate_stage', 'Placed', 6, true),
  ('candidate_stage', 'Alumni', 7, true),
  ('attendance_mark', 'P', 0, true),
  ('attendance_mark', 'A', 1, true),
  ('attendance_mark', 'L', 2, true),
  ('training_flag', 'On track', 0, false),
  ('training_flag', 'Needs help', 1, false),
  ('training_flag', 'At risk', 2, false),
  ('mock_level', 'L1', 0, false),
  ('mock_level', 'L2', 1, false),
  ('mock_status', 'Booked', 0, false),
  ('mock_status', 'Passed', 1, false),
  ('mock_status', 'Failed', 2, false),
  ('verdict', 'Ready', 0, false),
  ('verdict', 'Rebook', 1, false),
  ('verdict', 'Not ready', 2, false),
  ('resume_status', 'Pending', 0, false),
  ('resume_status', 'Approved', 1, false),
  ('resume_status', 'Rejected', 2, false),
  ('document_type', 'PAN', 0, false),
  ('document_type', 'Aadhaar', 1, false),
  ('document_type', 'Passport', 2, false),
  ('document_type', 'Degree certificate', 3, false),
  ('document_type', 'Experience letter', 4, false),
  ('document_type', 'Photo ID', 5, false),
  ('document_status', 'Missing', 0, false),
  ('document_status', 'Received', 1, false),
  ('document_status', 'Verified', 2, false),
  ('vendor', 'ResumeCo', 0, false),
  ('vendor', 'CheckFast', 1, false),
  ('vendor', 'ProfileWorks', 2, false),
  ('vendor_request_type', 'Resume rewrite', 0, false),
  ('vendor_request_type', 'LinkedIn polish', 1, false),
  ('vendor_request_type', 'Background check', 2, false),
  ('vendor_request_type', 'Certificate check', 3, false),
  ('request_status', 'Open', 0, false),
  ('request_status', 'In progress', 1, false),
  ('request_status', 'Done', 2, false),
  ('pf_status', 'Not applied', 0, false),
  ('pf_status', 'Applied, UAN awaited', 1, false),
  ('pf_status', 'UAN active', 2, false),
  ('pf_status', 'Not applicable', 3, false),
  ('paper_status', 'Requested', 0, false),
  ('paper_status', 'Received', 1, false),
  ('paper_status', 'Verified', 2, false),
  ('paper_status', 'Missing', 3, false),
  ('paper_status', 'Not due yet', 4, false),
  ('placement_status', 'Joining soon', 0, false),
  ('placement_status', 'Joined', 1, false),
  ('placement_status', 'Dropped', 2, false),
  ('checklist_status', 'Pending', 0, false),
  ('checklist_status', 'Done', 1, false),
  ('payment_mode', 'UPI', 0, false),
  ('payment_mode', 'Card', 1, false),
  ('payment_mode', 'Bank', 2, false),
  ('payment_mode', 'Cash', 3, false),
  ('payment_status', 'Due', 0, false),
  ('payment_status', 'Received', 1, false),
  ('payment_status', 'Overdue', 2, false),
  ('payment_status', 'Refund pending', 3, false),
  ('payment_status', 'Refunded', 4, false),
  ('campaign_channel', 'Meta ads', 0, false),
  ('campaign_channel', 'Google', 1, false),
  ('campaign_channel', 'YouTube', 2, false),
  ('campaign_channel', 'Referral', 3, false),
  ('campaign_channel', 'Offline', 4, false),
  ('campaign_status', 'Planned', 0, false),
  ('campaign_status', 'Live', 1, false),
  ('campaign_status', 'Paused', 2, false),
  ('campaign_status', 'Ended', 3, false),
  ('priority', 'High', 0, false),
  ('priority', 'Medium', 1, false),
  ('priority', 'Low', 2, false),
  ('company_status', 'Client', 0, false),
  ('company_status', 'Prospect', 1, false),
  ('company_status', 'Paused', 2, false),
  ('branch_mode', 'Classroom', 0, false),
  ('branch_mode', 'Online', 1, false),
  ('branch_mode', 'Hybrid', 2, false),
  ('batch_status', 'Upcoming', 0, false),
  ('batch_status', 'Live', 1, false),
  ('batch_status', 'Completed', 2, false)
on conflict do nothing;

insert into public.setting (key, value) values
  ('app_name', 'Stint CRM'), ('primary_colour', '#4474B9'), ('accent_colour', '#FF6B35'), ('font', 'Poppins'),
  ('default_theme', 'Light'), ('discount_approval_limit_pct', '10'), ('audio_retention_days', '90')
on conflict do nothing;

insert into public.program (name, duration_weeks, fee) values
  ('Data Engineering', 14, 60000), ('SAP FICO', 10, 65000), ('AI/ML', 12, 70000), ('Python', 6, 22000), ('Azure DE', 12, 58000)
on conflict do nothing;

insert into public.branch (name, city, mode) values ('HSR Layout', 'Bengaluru', 'Hybrid'), ('Online', null, 'Online') on conflict do nothing;

insert into public.lead_source (name, type, connection) values
  ('Meta lead form', 'Paid', 'Not set up'), ('Website form', 'Organic', 'Not set up'), ('Google lead form', 'Paid', 'Not set up'),
  ('YouTube link', 'Paid', 'Not set up'), ('Alumni referral link', 'Referral', 'Not set up'), ('Justdial', 'Paid', 'Not set up'),
  ('WhatsApp enquiry', 'Organic', 'Not set up'), ('Walk-in / phone', 'Offline', 'Manual'), ('Excel import', 'Offline', 'Manual')
on conflict do nothing;

insert into public.assignment_rule (when_text, give_to, method, limit_per_person) values
  ('New lead', 'Telecallers', 'Least busy first', '60 open leads each'),
  ('Lead marked Interested', 'Sales team', 'Least busy first', null),
  ('Lead converted', 'HR / Counsellors', 'By branch', '70 candidates each');

insert into public.follow_rule (trigger, suggest_next, after, stage, stuck_after_days) values
  ('Call: No answer', 'Call again', '1 day', 'Calls', 2),
  ('Call: Callback', 'Call back', 'At agreed time', 'Counselling', 5),
  ('Mock: Failed', 'Rebook mock', '3 days', 'Mocks', 10),
  ('Attendance: Absent', 'Call the student', 'Same day', 'Training', 90),
  ('Resume: Rejected', 'Fix and resubmit', '2 days', 'Resume + docs', 10),
  ('Fee: Overdue', 'Send reminder', 'Every 3 days', 'Placement', 30);

insert into public.connection (service, used_for) values
  ('Activepieces', 'Runs every automation'), ('WhatsApp Business', 'Messages to leads and candidates'),
  ('Email sender', 'Receipts, quotes, vendor emails'), ('Meta lead ads', 'Leads in'), ('Google lead forms', 'Leads in'),
  ('Online payments', 'Payments in, receipts'), ('SMS', 'Backup when WhatsApp fails'), ('Soniox', 'Live transcripts'), ('Gemini', 'Summaries')
on conflict do nothing;

insert into public.automation (name, direction, trigger, channel, recipient, message) values
  ('Meta lead → new lead', 'Incoming', 'Form submitted on Meta', null, 'Telecaller queue', null),
  ('Google lead → new lead', 'Incoming', 'Form submitted on Google', null, 'Telecaller queue', null),
  ('Online payment → fee record', 'Incoming', 'Payment succeeds', null, 'Finance', null),
  ('Welcome to new lead', 'Outgoing', 'Lead created', 'WhatsApp', 'Lead', 'Hi {name}, thanks for asking about {course} at Stint Academy. {caller} from our team will call you today.'),
  ('Lead assigned', 'Outgoing', 'Lead assigned', 'WhatsApp + in-app', 'Telecaller', 'New lead for you: {name}, {course}, from {source}. Call within 1 hour. Open: {link}'),
  ('Counselling reminder', 'Outgoing', 'Booked · 1 hr before', 'WhatsApp', 'Lead', 'Hi {name}, your counselling session with {counsellor} is at {time} today. Join here: {link}'),
  ('Fee quote and nudge', 'Outgoing', 'Quote sent · after 3 days', 'WhatsApp + email', 'Lead', 'Hi {name}, here is your fee quote for {course}: {amount}, with {discount} off. Valid until {date}. {link}'),
  ('Welcome and data sheet', 'Outgoing', 'Lead converted', 'WhatsApp + email', 'Candidate', 'Welcome to Stint Academy, {name}. Please fill your details here before the first class: {link}'),
  ('Fee due reminder', 'Outgoing', '3 days before · due day · every 3 days late', 'WhatsApp + email', 'Candidate', 'Hi {name}, your instalment of {amount} is due on {date}. Pay here: {link}. Ignore this if already paid.'),
  ('Payment receipt', 'Outgoing', 'Payment recorded', 'Email', 'Candidate', 'Hi {name}, we received {amount} on {date}. Receipt {receipt} is attached. Balance: {balance}.'),
  ('Absent today', 'Outgoing', 'Marked absent', 'WhatsApp', 'Candidate', 'Hi {name}, we missed you in {batch} today. The recording is here: {link}'),
  ('Mock reminder and result', 'Outgoing', '1 hr before · result saved', 'WhatsApp', 'Candidate', 'Hi {name}, your {level} mock with {sme} is at {time}. Join 5 minutes early: {link}'),
  ('Resume rejected', 'Outgoing', 'Resume rejected', 'Email', 'Candidate + HR', 'Hi {name}, your resume {version} needs changes: {reason}. Please upload a new version: {link}'),
  ('Vendor request', 'Outgoing', 'Request created', 'Email', 'Vendor', 'Hello, a new request from Stint Academy: {request} for {candidate}, due {date}. The file is attached.'),
  ('Placement congratulations', 'Outgoing', 'Offer recorded', 'WhatsApp', 'Candidate', 'Congratulations {name} on your offer from {company}! Your joining checklist is here: {link}'),
  ('Alumni check-in', 'Outgoing', 'Every 3 months', 'WhatsApp', 'Alumni', 'Hi {name}, how is it going at {company}? If a friend wants to join Stint, share this link: {link}'),
  ('Daily summary', 'Outgoing', 'Every day 9 AM', 'Email', 'Admin', 'Yesterday: {newLeads} new leads, {enrolled} enrolled, {collected} collected, {overdue} overdue, {stuck} stuck.');

-- Which roles own leads or candidates (Head vs Junior scoping, see migration team_scope)
update public.app_role set owns = '{lead}' where name in ('Telecaller', 'Sales');
update public.app_role set owns = '{candidate}' where name = 'HR / Counsellor';
update public.app_role set picks_up = '{Interested}' where name = 'Sales';
