import 'server-only';
import fontkit from '@pdf-lib/fontkit';
import { PDFDocument, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import fs from 'node:fs';
import path from 'node:path';

// Branded A4 fee quote and payment receipt in Poppins (TTF, which includes the ₹ sign).
const FONT_DIR = path.join(process.cwd(), 'node_modules/@expo-google-fonts/poppins');
const font = (f: string) => fs.readFileSync(path.join(FONT_DIR, f));
const LOGO = fs.readFileSync(path.join(process.cwd(), 'public/brand/stint-logo.svg'), 'utf8');

const BLUE = rgb(0x44 / 255, 0x74 / 255, 0xb9 / 255), INK = rgb(0x0f / 255, 0x25 / 255, 0x45 / 255), GREY = rgb(0x5f / 255, 0x6b / 255, 0x7e / 255),
  LINE = rgb(0xe6 / 255, 0xe9 / 255, 0xef / 255), SOFT = rgb(0xea / 255, 0xf2 / 255, 0xfb / 255), CORAL = rgb(1, 0x6b / 255, 0x35 / 255);
const hex = (h: string) => rgb(parseInt(h.slice(1, 3), 16) / 255, parseInt(h.slice(3, 5), 16) / 255, parseInt(h.slice(5, 7), 16) / 255);

export const inr = (n: number) => '₹' + Math.round(n).toLocaleString('en-IN');
const date = (d?: string | null) => (d ? new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : '—');

type Fonts = { reg: PDFFont; bold: PDFFont; rupee: PDFFont; rupeeBold: PDFFont };
export type Institute = { name: string; address: string; phone: string; email: string; gstin: string };

class Sheet {
  page: PDFPage; y: number; f: Fonts; W = 595.28; M = 48;
  constructor(page: PDFPage, f: Fonts) { this.page = page; this.f = f; this.y = 841.89 - 48; }
  /** Text that may contain ₹: the rupee sign comes from the latin-ext font. */
  text(t: string, x: number, y: number, size = 10, opts: { bold?: boolean; color?: ReturnType<typeof rgb>; right?: boolean } = {}) {
    const parts = t.split(/(₹)/).filter(Boolean);
    const fontOf = (p: string) => (p === '₹' ? (opts.bold ? this.f.rupeeBold : this.f.rupee) : opts.bold ? this.f.bold : this.f.reg);
    const width = parts.reduce((a, p) => a + fontOf(p).widthOfTextAtSize(p, size), 0);
    let cx = opts.right ? x - width : x;
    for (const p of parts) { const fo = fontOf(p); this.page.drawText(p, { x: cx, y, size, font: fo, color: opts.color || INK }); cx += fo.widthOfTextAtSize(p, size); }
    return width;
  }
  wrap(t: string, x: number, width: number, size = 9, color = GREY) {
    const words = t.split(/\s+/); let line = '';
    for (const w of words) {
      const next = line ? line + ' ' + w : w;
      if (this.f.reg.widthOfTextAtSize(next, size) > width && line) { this.text(line, x, this.y, size, { color }); this.y -= size + 4; line = w; } else line = next;
    }
    if (line) { this.text(line, x, this.y, size, { color }); this.y -= size + 4; }
  }
  rule(y = this.y, color = LINE) { this.page.drawLine({ start: { x: this.M, y }, end: { x: this.W - this.M, y }, thickness: 0.8, color }); }
}

async function start(inst: Institute, title: string, number: string, when: string) {
  const doc = await PDFDocument.create();
  doc.registerFontkit(fontkit);
  const f: Fonts = {
    reg: await doc.embedFont(font('400Regular/Poppins_400Regular.ttf'), { subset: true }),
    bold: await doc.embedFont(font('600SemiBold/Poppins_600SemiBold.ttf'), { subset: true }),
    rupee: undefined as unknown as PDFFont, rupeeBold: undefined as unknown as PDFFont,
  };
  f.rupee = f.reg; f.rupeeBold = f.bold;   // the TTF has ₹, so one font does it all
  doc.setTitle(`${title} ${number}`); doc.setAuthor(inst.name); doc.setCreator('Stint CRM');
  const s = new Sheet(doc.addPage([595.28, 841.89]), f);
  // logo: the SVG paths drawn directly, scaled to 34pt high
  const scale = 34 / 69;
  for (const m of LOGO.matchAll(/<path([^>]*)\sd="([^"]+)"([^>]*)fill="(#[0-9A-Fa-f]{6})"/g)) {
    const opacity = /opacity="([\d.]+)"/.exec(m[1] + m[3])?.[1];
    s.page.drawSvgPath(m[2], { x: s.M, y: s.y + 4, scale, color: hex(m[4]), opacity: opacity ? Number(opacity) : 1 });
  }
  s.text(title.toUpperCase(), s.W - s.M, s.y - 8, 16, { bold: true, color: BLUE, right: true });
  s.text(number, s.W - s.M, s.y - 24, 10, { color: GREY, right: true });
  s.text(when, s.W - s.M, s.y - 37, 9, { color: GREY, right: true });
  s.y -= 62;
  s.text(inst.name, s.M, s.y, 10, { bold: true });
  const contact = [inst.address, [inst.phone, inst.email].filter(Boolean).join(' · '), inst.gstin ? 'GSTIN ' + inst.gstin : ''].filter(Boolean);
  contact.forEach((c, i) => s.text(c, s.M, s.y - 13 * (i + 1), 8.5, { color: GREY }));
  s.y -= 13 * (contact.length + 1) + 6;
  s.rule(); s.y -= 22;
  return { doc, s };
}

function footer(s: Sheet, note: string) {
  s.y = Math.min(s.y, 120);
  s.rule(); s.y -= 16;
  s.wrap(note, s.M, s.W - 2 * s.M, 8.5);
  s.text('Generated by Stint CRM · ' + new Date().toLocaleString('en-IN'), s.M, 36, 7.5, { color: GREY });
}

export type QuoteData = { id: string; created_at: string; valid_until: string | null; status: string; list_price: number; discount_pct: number; amount: number;
  instalments: { label: string; amount: number; due_on?: string }[] | null; lead: { full_name: string; mobile?: string | null; email?: string | null; city?: string | null }; program: string; by?: string | null };

export async function quotePdf(q: QuoteData, inst: Institute, terms: string) {
  const number = 'Q-' + q.id.slice(0, 8).toUpperCase();
  const { doc, s } = await start(inst, 'Fee quote', number, 'Issued ' + date(q.created_at));
  const M = s.M, R = s.W - s.M;
  s.text('PREPARED FOR', M, s.y, 8, { bold: true, color: GREY });
  s.text('VALID UNTIL', R, s.y, 8, { bold: true, color: GREY, right: true });
  s.y -= 15;
  s.text(q.lead.full_name, M, s.y, 12, { bold: true });
  s.text(date(q.valid_until), R, s.y, 12, { bold: true, right: true, color: q.valid_until && new Date(q.valid_until) < new Date() ? CORAL : INK });
  s.y -= 14;
  s.text([q.lead.mobile, q.lead.email, q.lead.city].filter(Boolean).join(' · '), M, s.y, 9, { color: GREY });
  s.y -= 30;

  // price box
  s.page.drawRectangle({ x: M, y: s.y - 70, width: R - M, height: 82, color: SOFT });
  s.text('Program', M + 14, s.y - 6, 9, { color: GREY }); s.text(q.program, M + 14, s.y - 22, 13, { bold: true });
  s.text('List price', R - 250, s.y - 6, 9, { color: GREY }); s.text(inr(q.list_price), R - 250, s.y - 22, 11);
  s.text('Discount', R - 160, s.y - 6, 9, { color: GREY }); s.text(q.discount_pct ? q.discount_pct + '%' : '—', R - 160, s.y - 22, 11);
  s.text('You pay', R - 14, s.y - 6, 9, { color: GREY, right: true }); s.text(inr(q.amount), R - 14, s.y - 26, 18, { bold: true, color: BLUE, right: true });
  if (q.discount_pct) s.text('You save ' + inr(q.list_price - q.amount), R - 14, s.y - 46, 8.5, { color: GREY, right: true });
  s.y -= 104;

  // instalments
  const parts: { label: string; amount: number; due_on?: string }[] = q.instalments?.length ? q.instalments : [{ label: 'Full payment', amount: q.amount }];
  s.text('PAYMENT PLAN', M, s.y, 8, { bold: true, color: GREY }); s.y -= 8; s.rule(); s.y -= 16;
  parts.forEach((it, i) => {
    s.text(String(i + 1), M, s.y, 10, { color: GREY });
    s.text(it.label || 'Instalment ' + (i + 1), M + 22, s.y, 10);
    if (it.due_on) s.text(date(it.due_on), R - 120, s.y, 10, { color: GREY, right: true });
    s.text(inr(Number(it.amount)), R, s.y, 10, { bold: true, right: true });
    s.y -= 10; s.rule(); s.y -= 16;
  });
  s.text('Total', M + 22, s.y, 10, { bold: true }); s.text(inr(q.amount), R, s.y, 11, { bold: true, right: true, color: BLUE });
  s.y -= 34;
  if (q.by) { s.text('Your counsellor: ' + q.by, M, s.y, 9, { color: GREY }); s.y -= 20; }
  footer(s, terms);
  return { bytes: await doc.save(), filename: `Stint-fee-quote-${number}.pdf` };
}

export type ReceiptData = { id: string; receipt_no: string | null; amount: number; mode: string | null; paid_on: string | null; label: string | null;
  candidate: { full_name: string; code: string | null; program?: string | null }; balance?: number | null; total?: number | null; signature?: { png: string; signed_at: string } | null };

export async function receiptPdf(r: ReceiptData, inst: Institute, note: string) {
  const number = r.receipt_no || 'R-' + r.id.slice(0, 8).toUpperCase();
  const { doc, s } = await start(inst, 'Payment receipt', number, 'Paid ' + date(r.paid_on));
  const M = s.M, R = s.W - s.M;
  s.text('RECEIVED FROM', M, s.y, 8, { bold: true, color: GREY }); s.y -= 15;
  s.text(r.candidate.full_name, M, s.y, 12, { bold: true }); s.y -= 14;
  s.text([r.candidate.code, r.candidate.program].filter(Boolean).join(' · '), M, s.y, 9, { color: GREY }); s.y -= 30;

  s.page.drawRectangle({ x: M, y: s.y - 62, width: R - M, height: 74, color: SOFT });
  s.text('Amount received', M + 14, s.y - 6, 9, { color: GREY }); s.text(inr(r.amount), M + 14, s.y - 32, 22, { bold: true, color: BLUE });
  s.text('Mode', R - 200, s.y - 6, 9, { color: GREY }); s.text(r.mode || '—', R - 200, s.y - 22, 11);
  s.text('Towards', R - 14, s.y - 6, 9, { color: GREY, right: true }); s.text(r.label || 'Course fee', R - 14, s.y - 22, 11, { right: true });
  s.y -= 96;
  if (r.total != null) {
    s.text('Total fee', M, s.y, 10, { color: GREY }); s.text(inr(r.total), R, s.y, 10, { right: true }); s.y -= 10; s.rule(); s.y -= 16;
    s.text('Balance still due', M, s.y, 10, { bold: true }); s.text(inr(Math.max(0, r.balance || 0)), R, s.y, 11, { bold: true, right: true, color: (r.balance || 0) > 0 ? CORAL : BLUE });
    s.y -= 30;
  }
  s.page.drawRectangle({ x: R - 120, y: s.y - 8, width: 120, height: 26, borderColor: BLUE, borderWidth: 1.2, color: rgb(1, 1, 1) });
  const w = s.f.bold.widthOfTextAtSize('PAID', 12);
  s.text('PAID', R - 60 - w / 2, s.y, 12, { bold: true, color: BLUE });
  if (r.signature?.png) {   // the student's fee-agreement signature from the portal
    const img = await doc.embedPng(r.signature.png);
    const h = 44, wd = Math.min(160, (img.width / img.height) * h);
    s.page.drawImage(img, { x: M, y: s.y - 12, width: wd, height: h });
    s.text('Student’s signature on the fee agreement, ' + date(r.signature.signed_at), M, s.y - 24, 8, { color: GREY });
  }
  footer(s, note);
  return { bytes: await doc.save(), filename: `Stint-receipt-${number}.pdf` };
}

export async function institute(get: (k: string) => Promise<string>): Promise<Institute> {
  return { name: (await get('institute_name')) || 'Stint Academy', address: await get('institute_address'), phone: await get('institute_phone'), email: await get('institute_email'), gstin: await get('institute_gstin') };
}
